project:
  type: website
  output-dir: docs

website:
  title: "XDMarComs"
  navbar:
    left:
      #- href: index.qmd
      #  text: Home
      - href: tab1.qmd
        text: Programme Structure
      - href: tab2.qmd
        text: Faculty
      - href: tab3.qmd
        text: Requirements
      - href: tab4.qmd
        text: Applications Process
      - href: tab5.qmd
        text: News and Events
    logo: images/cutlogoo.png
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
