project:
  type: website
  output-dir: docs

website:
  title: "XDMarComs"
  navbar:
    left:
      #- href: index.qmd
      #  text: Home
      - href: tab1.qmd
        text: Tab One
      - href: tab2.qmd
        text: Tab Two
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
