---
title: "Application Instructions"
format: html
---


<style>
  a {
    color: blue;
  }
</style>


## Step 1
[Click here to create an account](https://sis2.cut.ac.cy/sap/bc/webdynpro/sap/zcut_wd_st_cr_account?sap-client=300&sap-language=EN#) and enter a valid e-mail address.

## Step 2
Follow the instructions you will receive on your personal e-mail to create your profile (personal information) in our system.  
Keep the access codes you will receive (username/password) to access the Portal.

## Step 3
From the web link [https://sis.cut.ac.cy/irj/portal](https://sis.cut.ac.cy/irj/portal) enter the username and password (as they were sent to your personal e-mail) in order to enter the Portal and to submit your application.

## Step 4
Select the *MSc Experiential and Digital Marketing communications* programme and attach the supporting documents required.

---

<p style="font-weight: bold; color: red; text-align: justify;">
  Notes: <br>
  1. Make sure you check your spam/junk/quarantine folders or ‘other’/’business’/ etc lists as system generated emails often get mislaid.<br>
  2. Please check your email regularly as we might need further documentation to process your application and also for updates on the selection process.
</p>

For any further questions please use the [application submission guide for programmes of study](https://www.cut.ac.cy/digitalAssets/76/76340_1Electronic_Application_for_CUT_Study_Programms__February_2022_.pdf) or contact the Services and Information Center:  
📞 +357 25002710 / 11  
📧 [kep@cut.ac.cy](e-mail at:kep@cut.ac.cy)
